### ISSUE TITLE
Transparent geometry rendering shows block artifacts

### ISSUE THREAD

**Issue by florianlink** [ospray/ospray#57]
I tried the transparency support in the scivis renderer of 0.10 and noticed some strange blocking artifacts on the transparent surfaces. These artifacts only appear on transparent geometry,
it looks fine when they are not transparent. The image has been rendered with accumulation and multiple passes. The more passes, the more evident the block structures become.
![screenshot_ospray0](https://cloud.githubusercontent.com/assets/5535644/15576964/ca89e880-235a-11e6-8c92-7ff97c2759b3.png)

**Comment by jeffamstutz** [comment]
Hi,

Could you verify that the bug still remains in the current ```devel``` branch? If it does, we can look into a good test case to reproduce, as we haven't come across this issue before.

Thanks,
Jeff

**Comment by ingowald** [comment]
I'm pretty sure I fixed this; but please double-check.

Ingo

**Comment by florianlink** [comment]
I updated to the current devel branch and tested again. I still get artifacts, but they look different,
see attached image. For reference, I also added a screenshot without transparency.
![screenshot_osprayliver_4](https://cloud.githubusercontent.com/assets/5535644/16952893/682d9966-4dcb-11e6-9879-2ffb96c25962.png)
![screenshot_osprayliver_5](https://cloud.githubusercontent.com/assets/5535644/16952894/682fd3de-4dcb-11e6-84c1-89880acd179f.png)

**Comment by johguenther** [comment]
If these artifacts are related to ray epsilon issues, chances are that they are fixed in v1.8 (in which self-intersection and ray epsilon are handled more robustly). However, it looks more like SIMD mask / uninitialized variable errors. In v2.0 the SciVis renderer will be cleaned-up, in which case this artifacts should be addressed as well.
