### ISSUE TITLE
Sometimes ospVolumeViewer crashes on Mac OS X 

### ISSUE THREAD

**Issue by syoyo** [ospray/OSPRay#7]
devel branch: 42d8f3510dbd5ddb7bf16a7971f35f68d3c57986
OS: MacOSX 10.8.5
Build: Release build
ISPC: v1.8.0

ospVoluimeViewer sometimes crashes for same input .osp. It looks like there's a memory-related bug in somewhere(near to ospFreeFrameBuffer?).

```
$ ../ospVolumeViewer input.osp
warning: ospFreeFrameBuffer not yet implemented - ignoring (this means there is a memory hole!)

$ ../ospVolumeViewer input.osp
ospVolumeViewer(48997,0x7fff74c78180) malloc: *** error for object 0x7ff5dbb0e0d8: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug

$ gdb ../ospVolumeViewer 
(gdb) b malloc_error_break
(gdb) set args lapP.osp
(gdb) r

…

Breakpoint 1, 0x00007fff8c0a0588 in malloc_error_break ()
(gdb) bt
#0  0x00007fff8c0a0588 in malloc_error_break ()
#1  0x00007fff8c0a9839 in szone_error ()
#2  0x00007fff8c0a7628 in szone_free_definite_size ()
#3  0x00007fff8c0a18c8 in free ()
#4  0x0000000101014ba3 in embree::Scene::build ()
#5  0x000000010100d8bf in rtcCommit ()
#6  0x000000010004e10d in ospCommit ()
#7  0x0000000100015873 in VolumeViewer::VolumeViewer ()
#8  0x0000000100003ba4 in main ()
```

**Comment by ingowald** [comment]
Hey, Syoyo,

Could you give us any more information as to where and how this 
happened? Any information regarding volume size, hardware config, ospray 
config (compiler, isa) would be useful. Anything else that looked 
suspicous before this crash happened? (eg, it getting ocnstantly slower, 
or memory filling up, or anything?)

As far as I can see from the gdb output the volumeviewer doesn't 
actually crash in any ospray code, but in the embree scene::build() 
function. I'll get the embree team involved as well, but any more 
information to track this down would be helpful.

Cheers,

Ingo

PS: The 'ospFreeFrameBuffer' will most likely not cause the memory 
corruption. The "memory hole" warning is a warning that a to-be-deleted 
framebuffer doesn't completely free all its memory yet, but I'm pretty 
sure that _that_ isn't the problem we're seeing here.

**Comment by syoyo** [comment]
Situation can be reproducible with tacc 256^3 data.

Performance looks OK if it runs finely.

```
$ ../ospVolumeViewer tacc-turbulence-256-volume.osp 
warning: ospFreeFrameBuffer not yet implemented - ignoring (this means there is a memory hole!)
^C
syoyo@mbp13-7:~/work/ospray-build/tacc-turbulence-256-volume$ ../ospVolumeViewer tacc-turbulence-256-volume.osp 
warning: ospFreeFrameBuffer not yet implemented - ignoring (this means there is a memory hole!)
^C
syoyo@mbp13-7:~/work/ospray-build/tacc-turbulence-256-volume$ ../ospVolumeViewer tacc-turbulence-256-volume.osp 
ospVolumeViewer(50453,0x7fff74c78180) malloc: *** error for object 0x7fb302e42c70: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
```

Here's more information about my configuration.

ISA: AVX(SandyBridge MacBook Pro)

```
$ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 5.1 (clang-503.0.38) (based on LLVM 3.4svn)
Target: x86_64-apple-darwin12.5.0
Thread model: posix

$ clang -v
clang version 3.5.0 (http://llvm.org/git/clang.git b1d67d0ce55d8ff0574341ec394c435828bf6ea4) (http://llvm.org/git/llvm.git 84a0dc323d90f86e899519b31b789ed5c0a0ec9a)
Target: x86_64-apple-darwin12.5.0
Thread model: posix
```

I am using source build of clang from git repo(not a release build), thus there might be a problem in clang I am using...

**Comment by svenwoop** [comment]
Which Embree version are you using? There were problems related to ansi-alias rules with GCC and CLANG in Embree versions prior to v2.4. Try to disable ansi-alias rules by using the clang.cmake files from Embree v2.4.

**Comment by syoyo** [comment]
OSPRay uses its own copy of Embree, and their version seems

```
#define __EMBREE_VERSION__ "2.3.3"
```

https://github.com/ospray/OSPRay/blob/master/ospray/embree/kernels/version.h

**Comment by ingowald** [comment]
I've (internally) updated ospray to embree 2.4 last night; Greg will do 
some more testing today and then push the changes out. Let's see if that 
fixes it!

**Comment by ingowald** [comment]
Weißt du noch was der diesbezüglich fix von 2.3.3 auf 2.4 war?

**Comment by gregjohnson** [comment]
Hi Syoyo,

We've been unable to reproduce the problem here, and suspect it may have to do with the version of clang that you're using.

We've pushed several updates, including updates to clang.cmake, that may help. We've delayed updating to Embree 2.4 due to issues revealed in testing.

Thanks,
Greg

**Comment by syoyo** [comment]
I have changed to use apple's clang, and updated ISPC 1.8.1, but the issue still happens.

```
$  clang -v
Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)
Target: x86_64-apple-darwin12.5.0
Thread model: posix
```

Thus suspicious component is Embree. When will OSPRay use Embree 2.4? I'll test again once OSPRay use Embree 2.4.

**Comment by syoyo** [comment]
> We've been unable to reproduce the problem here

And what is your OSX version?

**Comment by ingowald** [comment]
Syoyo,

Embree 2.4 uses some new c++11 extensions that have turned out to be 
incompatible with the majority of the systems that OSPRay supports; as 
such, we currently do not plan on upgrading to 2.4 until that is resolved.

That said, I'm somewhat doubtful that it's indeed an embree-2.3-vs-2.4 
problem. Yes, the *crash* you are seeing seems to happen is in the 
embree scene build, but in the particular case of the volume viewer the 
embree scene is actually _empty_ (you do have a volume in the volume 
viewer, but not polygons, and since volumes are handled outside of the 
embree layer the actual embree scene should be empty). That in turn 
indicates that it's highly unlikely that the bug is actually "in" 
embree, and that it's instead related to some sort of memory corruption 
or similar that happens before embree even gets called.

And since virtually all of us use Macs by default (none being able to 
reproduce your bug) that "kind of" points towards your non-default 
installation of llvm, clang, ispc, or similar. Could you try to 
reproduce on a mac that did not get patched with different 
llvm/clang/ispc versions?

Cheers,

Ingo

**Comment by gregjohnson** [comment]
Also, I should mention we've only been able to test here on OSX 10.9.5 and 10.10. We currently don't have access to a 10.8.5 machine (matching your OS version) to test on, though we will work to add that to our testing environment.

**Comment by syoyo** [comment]
> Could you try to reproduce on a mac that did not get patched with different
llvm/clang/ispc versions?

As I said, I changed to use Apple's default clang.

BTW, I switched to use gcc-4.8.2 to compile OSPRay and got the another interesting backtrace(with debug build on).

```
$ bt
(gdb) bt
#0  0x00007fff8c0a0588 in malloc_error_break ()
#1  0x00007fff8c0a9839 in szone_error ()
#2  0x00007fff8c0aac8c in tiny_free_list_remove_ptr ()
#3  0x00007fff8c0a3ed3 in szone_free ()
#4  0x00007fff8c0a6bc7 in szone_memalign ()
#5  0x00007fff8c0a171a in malloc_zone_memalign ()
#6  0x00007fff8c0a1f4e in posix_memalign ()
#7  0x00000001000d594a in Model_init ()
#8  0x00000001000cad1c in ospray::api::LocalDevice::commit (this=0x102e00b60, _object=0x102bc47d0) at /Users/syoyo/work/OSPRay/ospray/api/LocalDevice.cpp:148
#9  0x00000001000c79bd in ospCommit (object=0x102bc47d0) at /Users/syoyo/work/OSPRay/ospray/api/API.cpp:421
#10 0x000000010003a198 in VolumeViewer::importObjectsFromFile (this=0x102b30ce0, filename=@0x102bcef50) at /Users/syoyo/work/OSPRay/apps/volumeViewer/VolumeViewer.cpp:149
#11 0x000000010003967b in VolumeViewer::initObjects (this=0x102b30ce0, filenames=@0x7fff5fbff270) at /Users/syoyo/work/OSPRay/apps/volumeViewer/VolumeViewer.cpp:163
#12 0x000000010003882b in VolumeViewer (this=0x102b30ce0, filenames=@0x7fff5fbff270, showFrameRate=false, writeFramesFilename=<value temporarily unavailable, due to optimizations>) at /Users/syoyo/work/OSPRay/apps/volumeViewer/VolumeViewer.cpp:61
#13 0x00000001000380ec in VolumeViewer (this=0x102b30ce0, filenames=@0x7fff5fbff270, showFrameRate=false, writeFramesFilename={static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0xeb8ca894990c3 <Address 0xeb8ca894990c3 out of bounds>}}) at /Users/syoyo/work/OSPRay/apps/volumeViewer/VolumeViewer.cpp:66
#14 0x0000000100006298 in main (argc=2, argv=0x7fff5fbff328) at /Users/syoyo/work/OSPRay/apps/volumeViewer/main.cpp:171
```

And with this backtrace, I got an bug. 
In `ospray/common/Mode.ispc`, they try to allocate 0-length memory when `numGeometries` is 0.

With the following fix, there's no memory corruption seg fault on my side anymore!(both clang and gcc compiled ospVolumeViewer).

```
diff --git a/ospray/common/Model.ispc b/ospray/common/Model.ispc
index 9224e6c..9b519d5 100644
--- a/ospray/common/Model.ispc
+++ b/ospray/common/Model.ispc
@@ -43,7 +43,7 @@ export void Model_init(void *uniform _model, uniform int32 numGeometries, unifor
                                          RTC_INTERSECT_UNIFORM|RTC_INTERSECT_VARYING);
 
   if (model->geometry) delete[] model->geometry;
-  model->geometry = uniform new uniform uniGeomPtr[numGeometries];
+  if (numGeometries > 0) model->geometry = uniform new uniform uniGeomPtr[numGeometries];
   model->geometryCount = numGeometries;
 
   if (model->volumes) delete[] model->volumes;
```

**Comment by ingowald** [comment]
Ouch. I just looked up the ISO C standard spec on malloc(0), and though 
all implementations I've worked with so far have always returned NULL, 
the spec indeed does not specify what to do in this case, only that any 
such alllocated pointer should work with a 'free' - but ISPC of course 
does not say what a 'delete[]' on such a pointer will do, so we do have 
undefined behavior here.

We'll fix ASAP; there are in fact mulitple places where we assume that 
ISPC would handle 'new X[0]' cases via NULL pointers, and we'll have to 
go over the code to fix those.

Anyway - THANK YOU so much for finding that ... you have no idea how 
much time we spent trying to reproduce that on our side (where it 
doesn't happen); but now it'll be easy to fix. Thanks again!

Cheers,

Ingo
