### ISSUE TITLE
scivis renderer bug when normals are not provided

### ISSUE THREAD

**Issue by fogleman** [ospray/OSPRay#88]
We've been hunting down an issue in ParaView+OSPRay. Here I have reproduced it with just OSPRay.

Here's a triangle-mesh sphere with only ambient lighting. Normals are not provided.

![0](https://cloud.githubusercontent.com/assets/520208/19530393/aeff4fc8-9601-11e6-9878-f2a249b94fd5.png)

If I add this code after the `postIntersect` call in [SciVisRenderer.ispc](https://github.com/ospray/OSPRay/blob/master/ospray/render/scivis/SciVisRenderer.ispc#L528), it fixes the issue:

`dg.Ns = normalize(dg.Ns);`

![1](https://cloud.githubusercontent.com/assets/520208/19530395/b1a74b90-9601-11e6-9761-6e0bfe8ce6bd.png)

Turns out this caused one of the issues shown in this bug: https://github.com/ospray/OSPRay/issues/75

**Comment by demarle** [comment]
Should fix this too:
https://gitlab.kitware.com/paraview/paraview/issues/16919

**Comment by carsonbrownlee** [comment]
thanks for the bug report, postIntersect has a flag for normalizing.  Will look into why it's not being triggered

**Comment by carsonbrownlee** [comment]
fixed in 1b3540d318df1ed6ecca2e488a5184b1d501bab2

**Comment by demarle** [comment]
Thanks. Any chance of that being tagged on the release branch somewhere? No
big deal if not, we'll just use a patched tarball for paraview binaries if
too much hassle right now.


David E DeMarle
Kitware, Inc.
R&D Engineer
21 Corporate Drive
Clifton Park, NY 12065-8662
Phone: 518-881-4909

**Comment by jeffamstutz** [comment]
There are some KNC problems that I'm fixing related to #87, where I'd like to get a v1.1.1 patch release out ASAP for those. I can cherry-pick Carson's fix into that, which will end up on the ```release-1.1.x``` branch (and then ```master``` when the release is done). I don't think I have more than half a day's worth of work to get that all fixed.

Would tomorrow be too late to get a release tagged and out for the next ParaView release?

**Comment by demarle** [comment]
Tomorrow is totally fine. We will make rc3 late next week, that is expected
to become 5.2.0 final.

**Comment by jeffamstutz** [comment]
This is now fixed in our latest v1.1.1 release.

**Comment by demarle** [comment]
With that I can render things 100 times smaller than before and they won't be black but it doesn't fix the problem. I've got no guarantee of the size of things I'm given (floating point limitations not withstanding). This patch is closer even though unoptimized as 

diff --git a/ospray/math/vec.ih b/ospray/math/vec.ih
index 1e575c0..24614a0 100644
--- a/ospray/math/vec.ih
+++ b/ospray/math/vec.ih
@@ -584,7 +584,11 @@ inline vec3f normalize(const vec3f v, float &len)
 { len = sqrtf(dot(v,v)); return v * rcpf(len); }
 
 inline vec3f safe_normalize(const vec3f v)
-{ return v * (1.f/sqrtf(max(1e-8f,dot(v,v)))); }
+{ if (dot(v,v) != 0) 
+   return v * (1.f/sqrtf(dot(v,v))); 
+  else
+   return v * (1.f/sqrtf(max(1e-8f,dot(v,v)))); 
+}

**Comment by demarle** [comment]
Think I meant to say withstanding, not not withstanding. In any case I meant to say of course we'll eventually hit floating point precision limitations and that OK.

**Comment by carsonbrownlee** [comment]
hi Dave, I think we can just bump that to the limits of ieee float, e-37, without relying on conditionals.  I'll commit that to devel, let me know if that fixes it for you.  I'm wondering if this is necessary at all if we are using such small numbers however, since the sqrtf function does not appear to fault on sqrtf(0).

**Comment by demarle** [comment]
1e-37 works for me. I'll patch the ospray that paraview binaries use in the interim until it lands in ospray release.

**Comment by demarle** [comment]
Getting back to this. Just bumped PV's OSPRay from 1.1.0 to 1.1.2 to get the fix. It appears to work fine on Linux, but not on Windows. I will verify that my win build actually used 1.1.2 next.

**Comment by demarle** [comment]
nope, it built 1.1.0, my bad.
